name: Gabrielle Kerkow
title: Gabrielle Kerkow
description: "Homepage of Gabrielle Kerkow"
domain: gkerkow.com
url: https://www.gkerkow.com
baseurl: ""
linkedin: https://www.linkedin.com/in/gabrielle-kerkow-mbt-405802126/
github: https://github.com/gkerkow
markdown: kramdown
