name: Gabrielle Kerkow
title: Gabrielle Kerkow
description: "Homepage of Gabrielle Kerkow"
domain: gkerkow.github.io
url: https://gkerkow.github.io
baseurl: ""
linkedin: https://www.linkedin.com/in/gabrielle-kerkow-mbt-405802126/
github: https://github.com/gkerkow
markdown: kramdown
